![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [2]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.23.3


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [10]:
# your code goes here
print(np.zeros(10,dtype=int))
# np.array([0]*10)

'''
Difference between dtype=int ,dtype=np.int 

dtype=np.int - means in older times,they used np.int for integer data type.Currently,np.int is removed from the NUmpy Library
So,we must use dtype=int
'''

'''
Difference between dtype=int32 and dtype=int64

Main difference is,elements will store in 32 bits and 64 bits

32 bits means - Each element will take 4 bytes(Min - -2^31, Max - 2^31 - 1)
64 bits means - Each Element will take 8 bytes(Min - -2^63, Max - 2^63 - 1)
'''


[0 0 0 0 0 0 0 0 0 0]


'\nDifference between dtype=int32 and dtype=int64\n\nMain difference is,elements will store in 32 bits and 64 bits\n\n32 bits means - Each element will take 4 bytes(Min - -2^31, Max - 2^31 - 1)\n64 bits means - Each Element will take 8 bytes(Min - -2^63, Max - 2^63 - 1)\n'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [11]:
# your code goes here
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [ ]:
# your code goes here
np.ones([2,2],dtype=int)
# By default,values will be in float format 

array([[1, 1],
       [1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [14]:
# your code goes here
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [4]:
# your code goes here
X = np.array([1,2,3],dtype=int)
print(X)
Y = np.ones_like(X)
print(Y)

[1 2 3]
[1 1 1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [9]:
x=np.array([[1,2],[3,4]],dtype=int)
print(x)
y = np.zeros_like(x)
print(y)
'''
In python,it is possible to initialize one array to another like,
X = np.arange(4,dtypr=int)
Y = X
Whereas,In C,C++,Java it is not possible.
Here,Python Stands Unique
'''

[[1 2]
 [3 4]]
[[0 0]
 [0 0]]


'\nIn python,it is possible to initialize one array to another like,\nX = np.arange(4,dtypr=int)\nY = X\nWhereas,In C,C++,Java it is not possible.\nHere,Python Stands Unique\n'

Create a numpy matrix of 4*4 integers, filled with fives.

In [10]:
X = np.ones([4,4],dtype=int)*5
X

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [11]:
X = np.array([[1,2],[3,4],[5,6]],dtype=int)
Y = np.ones_like(X)*7
Y

array([[7, 7],
       [7, 7],
       [7, 7]])

Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [15]:
# np.identity(3,dtype=int)
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Create a numpy array, filled with 3 random integer values between 1 and 10.

In [19]:
np.random.randint(10,size=3)

array([7, 5, 8])

Create a 3 * 3 * 3 numpy matrix, filled with random float values.

In [23]:
# np.random.random((3,3,3))
np.random.randn(3,3,3)

array([[[-1.17424101, -0.36219071,  0.63827996],
        [ 0.76686044,  0.79766223,  0.00172114],
        [ 1.62854104, -0.16287709,  0.56659538]],

       [[ 1.69583999, -1.44227306, -1.6742095 ],
        [ 0.65443923,  0.40800086, -0.77763227],
        [-1.42684861, -0.73907376,  0.84415862]],

       [[ 0.66648767,  0.34614302, -0.53996034],
        [-0.26368533, -0.75021658,  0.18563017],
        [-0.57737779,  0.65837346, -0.32593727]]])

Given the X python list convert it to an Y numpy array

In [26]:
X=[1,2,3]
Y = np.array(X)
print(Y)
print(type(X),type(Y))

[1 2 3]
<class 'list'> <class 'numpy.ndarray'>


Given the X numpy array, make a copy and store it on Y.

In [ ]:
X = np.array([1,2,3,4,5])
Y = np.copy(X)
Y
print(id(X),id(Y))

'''
if we give,
Y = X - we will get the same address
If we use,np.copy we will get different address
'''

2801469252752 2801469252752


Create a numpy array with numbers from 1 to 10

In [3]:
X = np.arange(11)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create a numpy array with the odd numbers between 1 to 10

In [4]:
X = np.arange(1,11,2)
X

array([1, 3, 5, 7, 9])

Create a numpy array with numbers from 1 to 10, in descending order.

In [ ]:
X = np.arange(10,0,-1)
X
# X = np.arange(1,11)[::-1]
# X

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [9]:
X = np.arange(0,9).reshape(3,3)
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
X = np.zeros((10,10))
print(X)
print(X.size)
print(X.itemsize)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
100
8


                                            Array indexation

Given the X numpy array, show it's first element

In [2]:
X = np.array([1,2,3,4])
X[0]

1

Given the X numpy array, show it's last element

In [4]:
X = np.array([1,2,4,3])
X[-1]

3

Given the X numpy array, show it's first three elements

In [5]:
X = np.array([1,2,3,4])
X[:3]

array([1, 2, 3])

Given the X numpy array, show all middle elements

In [10]:
X = np.array([1,2,3,4])
X[1:-1]

array([2, 3])

Given the X numpy array, show the elements in reverse position

In [11]:
X = np.array([1,2,3,4])
X[::-1]

array([4, 3, 2, 1])

Given the X numpy array, show the elements in an odd position

In [12]:
X = np.array([1,2,3,4])
X[::2]

array([1, 3])

Given the X numpy matrix, show the first row elements

In [20]:
X = np.array([[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12],
     [13,14,15,16]
     ])
X[0]

array([1, 2, 3, 4])

Given the X numpy matrix, show the last row elements

In [21]:
X=np.array([[1,2,3,4],
   [5,6,7,8],
   [9,10,11,12],
   [13,14,15,16]
   ])
X[-1]

array([13, 14, 15, 16])

Given the X numpy matrix, show the first element on first row

In [ ]:
X = np.array([[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12],
     [13,14,15,16]
     ])
# X[0][0]
X[0, 0]
'''
if we give,
X = [[1,2],
     [3,4]]
It is considered as a list of list

If we give,
X = np.array([[1,2],
     [3,4]])
It is considered as a 2d Array
'''

1

Given the X numpy matrix, show the last element on last row

In [ ]:
X = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
X[-1][-1]
# X[-1,-1]


16

Given the X numpy matrix, show the middle row elements

In [ ]:
X = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
X[1:-1]
'''
The key NumPy slicing pattern is:
X[row_start:row_end, column_start:column_end]
'''

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Given the X numpy matrix, show the first two elements on the first two rows

In [32]:
X = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
X[0:2,0:2]

array([[1, 2],
       [5, 6]])

Given the X numpy matrix, show the last two elements on the last two rows

In [33]:
X = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
X[2:,2:]

array([[11, 12],
       [15, 16]])

Array manipulation  

Convert the given integer numpy array to float

In [5]:
X = [1,2,3,4]
Y = np.array(X,dtype=float)
Y

array([1., 2., 3., 4.])

Reverse the given numpy array (first element becomes last)

In [6]:
X = np.array([1,2,3,4],dtype=int)
X[::-1]

array([4, 3, 2, 1])

Order (sort) the given numpy array

In [9]:
X = np.array([4,1,2,3],dtype=int)
X.sort()
X

array([1, 2, 3, 4])

Given the X numpy array, set the fifth element equal to 1

In [16]:
a = np.array([1,2,3,4,5,6,7,8,9])
# X[4]=1
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Given the X numpy array, change the 50 with a 40

In [17]:
X = np.array([1,50,80,12])
X[1]=40
X

array([ 1, 40, 80, 12])

Given the X numpy matrix, change the last row with all 1

In [18]:
X = np.array([
    [1,2,3],
    [4,5,6,],
    [7,8,9]
])
X[-1]=[1,1,1]
X

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

Given the X numpy matrix, change the last item on the last row with a 0

In [20]:
X = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
# X[-1,-1]=0
X[2,2]=0
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

Given the X numpy matrix, add 5 to every element

In [ ]:
X = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
X+5
# If we simply give X+5, original array elements doesn't gets changed
# If we give,X=X+5,then original array gets changed

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Boolean arrays (also called masks)

Given the X numpy array, make a mask showing negative elements

In [5]:
X = np.array([-1,2,5,-9,-6,0,-3])
temp=X<0
temp

array([ True, False, False,  True,  True, False,  True])

Given the X numpy array, get the negative elements

In [6]:
X = np.array([-1,2,5,-9,-6,0,-3])
temp = X<0
X[temp]

array([-1, -9, -6, -3])

Given the X numpy array, get numbers higher than 5

In [9]:
X = np.array([12,2,5,9,8,7])
temp = X>5
X[temp]

array([12,  9,  8,  7])

Given the X numpy array, get numbers higher than the elements mean

In [13]:
X=np.array([12,2,5,9,8,7])
print(X.mean())
temp = X > X.mean()
X[temp]

7.166666666666667


array([12,  9,  8])

Given the X numpy array, get numbers equal to 2 or 10

In [ ]:
X = np.array([12,2,5,9,8,7,10,2])
temp = (X==2) | (X==10)
X[temp]
'''
and, or, not → ordinary Python Boolean values(which will check the Single boolean value(i.e. it will produce either true or false))
&, |, ~ → element-wise NumPy Boolean operations(which will check element-by-element in Arrays)
'''

array([ 2, 10,  2])

Logic Functions

Given the X numpy array, return True if none of its elements is zero

In [4]:
X = np.array([1,2,3,4,5,0])
X.all()

False

Given the X numpy array, return True if any of its elements is zero

In [ ]:
X = np.array([0,9,0,0,0])
X.any()
# .all - will check all elements are True?
# .any() - will chrck any of the element is true? 

True

Summary statistics

Given the X numpy array, show the sum of its elements

In [9]:
X = np.array([1,2,3,4,5])
X.sum()

15

Given the X numpy array, show the mean value of its elements

In [10]:
X = np.array([[1,2,3,4,5]])
X.mean()

3.0

Given the X numpy matrix, show the sum of its columns

In [ ]:
X = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])
X.sum(axis=0)
# axis=0 - Sum of Columns
# axis=1 - Sum of rows

array([18, 21, 24, 27, 30])

Given the X numpy matrix, show the mean value of its rows

In [16]:
X = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])
X.mean(axis=1)
print(type(X))
print(X.dtype)

<class 'numpy.ndarray'>
int32


Given the X numpy array, show the max value of its elements

In [15]:
X = np.array([1,2,3,5,25,6])
X.max()

25