![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.23.3


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [10]:
# your code goes here
print(np.zeros(10,dtype=int))
# np.array([0]*10)

'''
Difference between dtype=int ,dtype=np.int 

dtype=np.int - means in older times,they used np.int for integer data type.Currently,np.int is removed from the NUmpy Library
So,we must use dtype=int
'''

'''
Difference between dtype=int32 and dtype=int64

Main difference is,elements will store in 32 bits and 64 bits

32 bits means - Each element will take 4 bytes(Min - -2^31, Max - 2^31 - 1)
64 bits means - Each Element will take 8 bytes(Min - -2^63, Max - 2^63 - 1)
'''


[0 0 0 0 0 0 0 0 0 0]


'\nDifference between dtype=int32 and dtype=int64\n\nMain difference is,elements will store in 32 bits and 64 bits\n\n32 bits means - Each element will take 4 bytes(Min - -2^31, Max - 2^31 - 1)\n64 bits means - Each Element will take 8 bytes(Min - -2^63, Max - 2^63 - 1)\n'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [11]:
# your code goes here
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [ ]:
# your code goes here
np.ones([2,2],dtype=int)
# By default,values will be in float format 

array([[1, 1],
       [1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [14]:
# your code goes here
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [4]:
# your code goes here
X = np.array([1,2,3],dtype=int)
print(X)
Y = np.ones_like(X)
print(Y)

[1 2 3]
[1 1 1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [9]:
x=np.array([[1,2],[3,4]],dtype=int)
print(x)
y = np.zeros_like(x)
print(y)
'''
In python,it is possible to initialize one array to another like,
X = np.arange(4,dtypr=int)
Y = X
Whereas,In C,C++,Java it is not possible.
Here,Python Stands Unique
'''

[[1 2]
 [3 4]]
[[0 0]
 [0 0]]


'\nIn python,it is possible to initialize one array to another like,\nX = np.arange(4,dtypr=int)\nY = X\nWhereas,In C,C++,Java it is not possible.\nHere,Python Stands Unique\n'

Create a numpy matrix of 4*4 integers, filled with fives.

In [10]:
X = np.ones([4,4],dtype=int)*5
X

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [11]:
X = np.array([[1,2],[3,4],[5,6]],dtype=int)
Y = np.ones_like(X)*7
Y

array([[7, 7],
       [7, 7],
       [7, 7]])

Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [15]:
# np.identity(3,dtype=int)
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Create a numpy array, filled with 3 random integer values between 1 and 10.

In [19]:
np.random.randint(10,size=3)

array([7, 5, 8])

Create a 3 * 3 * 3 numpy matrix, filled with random float values.

In [23]:
# np.random.random((3,3,3))
np.random.randn(3,3,3)

array([[[-1.17424101, -0.36219071,  0.63827996],
        [ 0.76686044,  0.79766223,  0.00172114],
        [ 1.62854104, -0.16287709,  0.56659538]],

       [[ 1.69583999, -1.44227306, -1.6742095 ],
        [ 0.65443923,  0.40800086, -0.77763227],
        [-1.42684861, -0.73907376,  0.84415862]],

       [[ 0.66648767,  0.34614302, -0.53996034],
        [-0.26368533, -0.75021658,  0.18563017],
        [-0.57737779,  0.65837346, -0.32593727]]])

Given the X python list convert it to an Y numpy array

In [26]:
X=[1,2,3]
Y = np.array(X)
print(Y)
print(type(X),type(Y))

[1 2 3]
<class 'list'> <class 'numpy.ndarray'>


Given the X numpy array, make a copy and store it on Y.

In [ ]:
X = np.array([1,2,3,4,5])
Y = np.copy(X)
Y
print(id(X),id(Y))

'''
if we give,
Y = X - we will get the same address
If we use,np.copy we will get different address
'''

2801469252752 2801469252752
